/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    testimonials: Testimonial;
    faqs: Faq;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    header: Header;
    footer: Footer;
    'closing-cta': ClosingCta;
    'service-page-sections': ServicePageSection;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'closing-cta': ClosingCtaSelect<false> | ClosingCtaSelect<true>;
    'service-page-sections': ServicePageSectionsSelect<false> | ServicePageSectionsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The three services. Each one powers its own page, its home page card and the Services menu. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Each service is tied to its own page and colour theme.
   */
  slug: 'coaching' | 'tarot' | 'reiki';
  /**
   * Used in the colour key on the home page, e.g. “Coaching”.
   */
  shortName: string;
  /**
   * One-word theme, e.g. “Clarity”.
   */
  tag: string;
  icon: number | Media;
  cardDescription: string;
  /**
   * Short line shown in the header Services dropdown.
   */
  navShort: string;
  hero: {
    eyebrow: string;
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    description: string;
    /**
     * Short chips shown under the hero and in the booking section.
     */
    trust?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    tone?: ('lavender' | 'sage' | 'opal') | null;
  };
  intro: string;
  pullQuote: string;
  overview: {
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    subline: string;
  };
  /**
   * Exactly three benefits — the middle one is highlighted.
   */
  benefits?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — defaults to the photo set in “Service page sections”.
   */
  sessionsImage?: (number | null) | Media;
  seo: {
    title: string;
    description: string;
  };
  sessions?:
    | {
        name: string;
        price: string;
        duration: string;
        format: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  expectations?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  bookingLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos and service icons used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers. Used wherever the image is meaningful.
   */
  alt: string;
  _objectKey?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The home page shows the first three, in this order. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  _order?: string | null;
  /**
   * Short headline, e.g. “Feeling calmer & clearer”.
   */
  theme: string;
  quote: string;
  /**
   * e.g. “Coaching client”.
   */
  cite: string;
  /**
   * Highlight this card (works best on the middle card).
   */
  spotlight?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shown on the home and contact pages, in this order. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  _order?: string | null;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  shortName?: T;
  tag?: T;
  icon?: T;
  cardDescription?: T;
  navShort?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        script?: T;
        description?: T;
        trust?:
          | T
          | {
              text?: T;
              id?: T;
            };
        tone?: T;
      };
  intro?: T;
  pullQuote?: T;
  overview?:
    | T
    | {
        title?: T;
        script?: T;
        subline?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  sessionsImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  sessions?:
    | T
    | {
        name?: T;
        price?: T;
        duration?: T;
        format?: T;
        description?: T;
        id?: T;
      };
  expectations?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  bookingLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  theme?: T;
  quote?: T;
  cite?: T;
  spotlight?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  _order?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    eyebrow: string;
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    lead: string;
    primaryCta: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
    secondaryCta: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
    trust?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    backgroundImage: number | Media;
  };
  values?:
    | {
        icon: 'pace' | 'personal' | 'holistic';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  servicesSection: {
    eyebrow: string;
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    lead: string;
    cardButtonLabel: string;
    footerBefore: string;
    footerAfter?: string | null;
    footerLink: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
  };
  meetCara: {
    eyebrow: string;
    /**
     * e.g. “Hi, I'm”
     */
    greeting: string;
    /**
     * Shown in script.
     */
    name: string;
    quote: string;
    body: string;
    essence?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    cta: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
    note: string;
    badge: string;
    portrait: number | Media;
  };
  testimonialsSection: {
    eyebrow: string;
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    lead: string;
    footerText: string;
    cta: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
  };
  seo: {
    title: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    eyebrow: string;
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    lead: string;
    primaryCta: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
    secondaryCta: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
    trust?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    badge: string;
    portrait: number | Media;
  };
  story: {
    eyebrow: string;
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    sub: string;
    lead: string;
    detail: string;
    facts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
    caption: string;
  };
  essence: {
    kicker: string;
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    intro: string;
    /**
     * Large faint background words.
     */
    watermark?: string | null;
    items?:
      | {
          icon: 'pace' | 'personal' | 'holistic';
          accent: 'personal' | 'holistic' | 'pace';
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  path: {
    kicker: string;
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    intro: string;
    steps?:
      | {
          icon: 'pace' | 'personal' | 'holistic';
          accent: 'coaching' | 'tarot' | 'reiki';
          tag: string;
          title: string;
          text: string;
          note: string;
          id?: string | null;
        }[]
      | null;
  };
  seo: {
    title: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The contact and FAQ sections appear on both the Contact page and the Home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  contact: {
    eyebrow: string;
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    lead: string;
    emailLabel: string;
    emailNote: string;
    socialLabel: string;
    locationTitle: string;
    locationText: string;
    trust?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  form: {
    title: string;
    note: string;
    promise: string;
    nameLabel: string;
    namePlaceholder?: string | null;
    emailLabel: string;
    emailPlaceholder?: string | null;
    emailHint?: string | null;
    serviceLabel: string;
    servicePlaceholder: string;
    serviceOptions?:
      | {
          label: string;
          /**
           * Short code sent with the message, e.g. “coaching”.
           */
          value: string;
          id?: string | null;
        }[]
      | null;
    messageLabel: string;
    submitLabel: string;
    messagePlaceholder?: string | null;
  };
  faqsSection: {
    eyebrow: string;
    title: string;
    lead: string;
  };
  seo: {
    title: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The menu at the top of every page, including the Services dropdown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  linksBeforeServices?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  servicesLabel: string;
  linksAfterServices?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  bookCta: {
    label: string;
    /**
     * A page path such as /bookings, or a section anchor such as #contact.
     */
    href: string;
  };
  mobileContactCta: {
    label: string;
    /**
     * A page path such as /bookings, or a section anchor such as #contact.
     */
    href: string;
  };
  dropdown: {
    eyebrow: string;
    script: string;
    lead: string;
    cta: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
    /**
     * Text before the footnote link.
     */
    footnote: string;
    footnoteLink: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The welcome message, links and contact details at the bottom of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  title: string;
  /**
   * Shown in the handwritten accent font.
   */
  script: string;
  calmText: string;
  blurb: string;
  brandScript: string;
  exploreHeading: string;
  exploreLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contactHeading: string;
  locationLines?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    /**
     * A page path such as /bookings, or a section anchor such as #contact.
     */
    href: string;
  };
  bottomLink: {
    label: string;
    /**
     * A page path such as /bookings, or a section anchor such as #contact.
     */
    href: string;
  };
  /**
   * The current year is added automatically.
   */
  copyrightName: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The “Take the first step” block at the bottom of the About and service pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "closing-cta".
 */
export interface ClosingCta {
  id: number;
  eyebrow: string;
  title: string;
  /**
   * Shown in the handwritten accent font.
   */
  script: string;
  lead: string;
  assurances?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cardTitle: string;
  cardText: string;
  primaryCta: {
    label: string;
    /**
     * A page path such as /bookings, or a section anchor such as #contact.
     */
    href: string;
  };
  secondaryCta: {
    label: string;
    /**
     * A page path such as /bookings, or a section anchor such as #contact.
     */
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Wording shared by the Coaching, Tarot and Reiki pages. Service-specific text is edited under Content → Services.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-page-sections".
 */
export interface ServicePageSection {
  id: number;
  hero: {
    primaryCta: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
    secondaryCta: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
  };
  overview: {
    captionScript: string;
    captionNote: string;
  };
  benefits: {
    kicker: string;
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    sub: string;
  };
  sessions: {
    kicker: string;
    title: string;
    /**
     * Shown in the handwritten accent font.
     */
    script: string;
    lead: string;
    steps?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    primaryCta: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
    secondaryCta: {
      label: string;
      /**
       * A page path such as /bookings, or a section anchor such as #contact.
       */
      href: string;
    };
    caption: string;
    /**
     * Used when a service has no booking section photo of its own.
     */
    fallbackImage: number | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  tagline: string;
  email: string;
  /**
   * Used in search engine data, e.g. “Chichester & Eastergate, West Sussex”.
   */
  location: string;
  /**
   * Leave blank to hide. Icons appear in the contact section and footer.
   */
  social?: {
    facebook?: string | null;
    instagram?: string | null;
  };
  seo: {
    /**
     * Used when a page has no description of its own.
     */
    description: string;
    image: number | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        script?: T;
        lead?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        trust?:
          | T
          | {
              text?: T;
              id?: T;
            };
        backgroundImage?: T;
      };
  values?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  servicesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        script?: T;
        lead?: T;
        cardButtonLabel?: T;
        footerBefore?: T;
        footerAfter?: T;
        footerLink?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  meetCara?:
    | T
    | {
        eyebrow?: T;
        greeting?: T;
        name?: T;
        quote?: T;
        body?: T;
        essence?:
          | T
          | {
              text?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        note?: T;
        badge?: T;
        portrait?: T;
      };
  testimonialsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        script?: T;
        lead?: T;
        footerText?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        script?: T;
        lead?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        trust?:
          | T
          | {
              text?: T;
              id?: T;
            };
        badge?: T;
        portrait?: T;
      };
  story?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        script?: T;
        sub?: T;
        lead?: T;
        detail?: T;
        facts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        caption?: T;
      };
  essence?:
    | T
    | {
        kicker?: T;
        title?: T;
        script?: T;
        intro?: T;
        watermark?: T;
        items?:
          | T
          | {
              icon?: T;
              accent?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  path?:
    | T
    | {
        kicker?: T;
        title?: T;
        script?: T;
        intro?: T;
        steps?:
          | T
          | {
              icon?: T;
              accent?: T;
              tag?: T;
              title?: T;
              text?: T;
              note?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        script?: T;
        lead?: T;
        emailLabel?: T;
        emailNote?: T;
        socialLabel?: T;
        locationTitle?: T;
        locationText?: T;
        trust?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  form?:
    | T
    | {
        title?: T;
        note?: T;
        promise?: T;
        nameLabel?: T;
        namePlaceholder?: T;
        emailLabel?: T;
        emailPlaceholder?: T;
        emailHint?: T;
        serviceLabel?: T;
        servicePlaceholder?: T;
        serviceOptions?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        messageLabel?: T;
        submitLabel?: T;
        messagePlaceholder?: T;
      };
  faqsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  linksBeforeServices?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  servicesLabel?: T;
  linksAfterServices?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  bookCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  mobileContactCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  dropdown?:
    | T
    | {
        eyebrow?: T;
        script?: T;
        lead?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        footnote?: T;
        footnoteLink?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  title?: T;
  script?: T;
  calmText?: T;
  blurb?: T;
  brandScript?: T;
  exploreHeading?: T;
  exploreLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contactHeading?: T;
  locationLines?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  bottomLink?:
    | T
    | {
        label?: T;
        href?: T;
      };
  copyrightName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "closing-cta_select".
 */
export interface ClosingCtaSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  script?: T;
  lead?: T;
  assurances?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cardTitle?: T;
  cardText?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-page-sections_select".
 */
export interface ServicePageSectionsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  overview?:
    | T
    | {
        captionScript?: T;
        captionNote?: T;
      };
  benefits?:
    | T
    | {
        kicker?: T;
        title?: T;
        script?: T;
        sub?: T;
      };
  sessions?:
    | T
    | {
        kicker?: T;
        title?: T;
        script?: T;
        lead?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        caption?: T;
        fallbackImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  email?: T;
  location?: T;
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
      };
  seo?:
    | T
    | {
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}