/* Generated by Payload, then customised: passes the site fonts to the admin (htmlProps). */
/* Keep that change if Payload ever regenerates this file. */
import config from '@payload-config'
import '@payloadcms/next/css'
import type { ServerFunctionClient } from 'payload'
import { handleServerFunctions, RootLayout } from '@payloadcms/next/layouts'
import React from 'react'

import { cormorant, manrope, sacramento } from '@/lib/fonts'

import { importMap } from './admin/importMap.js'
import './custom.scss'

type Args = {
  children: React.ReactNode
}

const serverFunction: ServerFunctionClient = async function (args) {
  'use server'
  return handleServerFunctions({
    ...args,
    config,
    importMap,
  })
}

const Layout = ({ children }: Args) => (
  <RootLayout
    config={config}
    importMap={importMap}
    serverFunction={serverFunction}
    // Site fonts for the admin theme (see custom.scss)
    htmlProps={{ className: `${manrope.variable} ${cormorant.variable} ${sacramento.variable}` }}
  >
    {children}
  </RootLayout>
)

export default Layout
